---
title: "IE 360"
author: "Group1"
date: "22 06 2020"
output: html_document
---

```{r setup, include=FALSE}


knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

Forecasting the sales quantity of a product is important for online retails, they must take their decisions based on the forecasts and the forecast accuracy becomes important to minimize any stockouts and also the inventory holding cost. With the vast amount of data available for the e-commerce companies, forecasting the sales becomes an important task for the companies.

\ In the project, our main task is to forecast eight different products of Trendyol in a daily basis. This forecast is done every day and it is done nearly for almost 30 days. The forecast is done for tomorrow given the sales data up until yesterday.

\ Our project data was very detailed, it was consisting of different features which are event_date, product_content_id, sold_count, visit_count, favored_count, basket_count, category_sold, category_brand_sold, category_visits, ty_visits and price. The earliest date was from one year before and it was updated each day by adding the new day's information. Sold count is the variable that we wanted to forecast for tomorrow for each product.

\ We prepared the data by removing NA values, removing some columns such as event_date and product_content_id, adding some features such as is_after_corona which describes if the date of the sales is after the first case of corona or not and some lagged sold_count variables such as lag_1, lag_7, lag_28 and lag_365. We then transformed the data into xts and grouped the data by 8, which are the products.

\ Our main approach to the problem can be summarized as; we first analyzed the data and after preparing the data, by using forecasting methods, we had come up with the different results. By using different evaluation criteria such as fixed origin and rolling origin, and by determining the interval of data to train the forecast, we had come up with a solution for the project. We have also used information from Trendyol's website such as stock or price and we used our insight's such as the lifting of quarantine measures (June 1), special days(bayram) and weather forecast to gain insight and forecast more accurately.


## Related Literature

The course materials, and the lectures from Datacamp are used extensively in developing an approach to the project. Other than that, we made literature search.

In the article "Sales Forecasting for Fashion Retailing Service Industry: A Review", it talks about how the forecasts are strongly affected by seasonal factors, fashion trend factor and other tricky variables. We concluded from the article that holidays are very important in determining the sales quantity. We have also concluded that statistical methods can be used for short-term forecasts.

We have also used Rob Hyndman's "Forecasting: Principles and Practice". In this book, lots of different forecasting methods are discussed and we have used most of the methods there and evaluated them with each other to be more accurate in sales predictions.

You can find the related articles in reference.


## Approach

\ In this project, we used different methods which are Naive, Mean, Holt Winters Additive, Holt Winters Multiplicative, Exponential Smoothing, Auto Arima, TBATS, Linear Regression, Backward Stepwise Regression, Forward Stepwise Regression and Neural Network. Linear regression and stepwise regression are regression methods which needs external regressors whereas other methods can just use the sold_count data. We used sold_count data in these methods except for regression models.

\ Naive method is a very basic method which gives but it is important in some cases where it is not possible to predict the direction of change in the next day's sales. Example of this could be Tayt sales, sometimes stockouts happened and large sales differences were present in consecutive days.

\ Mean method was useful in some cases where the variance is small. An example for this could be Süpürge and Yüz Temizleyici sales. In some cases they followed quite similar sales in the last 7 days and by shortening the time period, mean could be useful in sales prediction.

\ Holt Winters methods were added to detect seasonality and to make more accurate predictions. We thought that this approach could detect the weekday-weekend differences and could reflect it in the predictions. We used frequency of 7 days in our time series data, which makes it a weekly data.

\ Exponential Smoothing and Auto Arima methods were used with default lambda and auto lambda, which uses Box-Cox transformation. We wanted to use these methods to diversify our methods with the most basic ones and Auto Arima could add any autoregressive feature of the data.

\ Linear Regression and Stepwise Regression were used to improve the accuracy, but it needed external regressors and because that tomorrow's regressors were not available to us, we used today's features.

\ We used TBATS to detect any complicated seasonal pattern, which was also discussed in the book that we used to develop an approach. You can find it at reference section. Neural Network model was also used with auto lambda. In the book, this was also discussed and we used it to detect any complex non linear relationship in the data.

\ Before applying the methods, we have transformed the data to xts. Also, we have divided the data into 8 product groups. We have removed then the columns event_date and product_content_id. Lastly, we have added lagged sales count features which are lag1_sold_count, lag7_sold_count, lag28_sold_count and lag365_sold_count and we changed the price value where it was -1 with the recent price value.

\ We have used fixed origin and rolling origin to evaluate our forecast's accuracy. In the fixed origin evaluation, we used 2 types: one with the 80-20 percent train and test data ratio. The other was to use all data except the last 2 for train and the last 2 for the test data(today and tomorrow). We also thought that this project should be consistent for almost 30 days, so we used rolling origin approach. In this approach, we used the last 2 data to forecast and it was constant. However we increased the train data one by one. We used this method for the 20 percent of the data. This means we first used 80 percent of the data and divided into train and test data. Then increased the train data one by one up until it covers the whole data except the last 2 data. This can be summarized as increasing input and constant output. By using rolling origin, we aimed to achieve a more consistent forecasting approach.

